---
- name: create download folder for ipfs-update
  become: yes
  file:
    state: directory
    owner: root
    group: root
    dest: /opt/ipfs-update/{{ipfs_update_version}}

- name: download and unpack ipfs-update
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ dist_url }}/ipfs-update/{{ipfs_update_version}}/ipfs-update_{{ipfs_update_version}}_linux-{{ipfs_update_arch}}.tar.gz"
    dest: /opt/ipfs-update/{{ipfs_update_version}}
    creates: /opt/ipfs-update/{{ipfs_update_version}}/ipfs-update

- name: link ipfs-update executable
  become: yes
  file:
    state: link
    owner: root
    group: root
    dest: /usr/local/bin/ipfs-update
    src: /opt/ipfs-update/{{ipfs_update_version}}/ipfs-update/ipfs-update

- name: install ipfs
  become: yes
  command: ipfs-update install {{ipfs_version}}
  args:
    creates: /usr/local/bin/ipfs

- name: install ipfs init service
  become: yes
  copy:
    src: etc/systemd/system/ipfs.service
    dest: /etc/systemd/system/ipfs.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart IPFS

- name: make ipfs group
  become: yes
  group:
    state: present
    name: ipfs

- name: make ipfs user
  become: yes
  user:
    state: present
    name: ipfs
    group: ipfs
    shell: /bin/bash
    home: /home/ipfs
    comment: IPFS user
    system: yes

- name: copy default config
  become: yes
  become_user: ipfs
  template:
    src: home/ipfs/ipfs_default_config
    dest: /home/ipfs/ipfs_default_config
    owner: ipfs
    group: ipfs
    mode: 0644
  notify: restart IPFS

- name: init IPFS
  become: yes
  become_user: ipfs
  command: ipfs init --empty-repo -- /home/ipfs/ipfs_default_config
  args:
    creates: /home/ipfs/.ipfs/config
  notify: restart IPFS

- name: reload systemd
  become: yes
  systemd:
    daemon_reload: yes

- name: enable and start IPFS
  become: yes
  service:
    name: ipfs
    state: started
    enabled: yes
    use: systemd
