- name: reload systemd
  become: yes
  systemd:
    daemon_reload: yes
    name: ipfs
  notify: restart IPFS

- name: restart IPFS
  become: yes
  service:
    name: ipfs
    enabled: yes
    state: restarted
    use: systemd
